SELECT patients.last_name FROM patients;
SELECT patients.first_name,patients.last_name FROM patients WHERE patients.gender='male' AND patients.age>=18;
SELECT avg(patients.age) FROM patients;
SELECT count(1) FROM patients WHERE patients.diagnosis='flu';
SELECT patients.diagnosis,max(patients.age) FROM patients GROUP BY patients.diagnosis;
SELECT patients.diagnosis,max(patients.age) FROM patients WHERE patients.length_of_stay>=3 GROUP BY patients.diagnosis;
SELECT patients.age FROM patients;
SELECT patients.first_name,patients.age FROM patients WHERE patients.gender='male' OR patients.age>=18;
SELECT min(patients.age) FROM patients;
SELECT min(patients.length_of_stay) FROM patients WHERE patients.gender='male';
SELECT patients.gender,min(patients.length_of_stay) FROM patients GROUP BY patients.gender;
SELECT patients.gender,min(patients.length_of_stay) FROM patients WHERE patients.diagnosis='flu' GROUP BY patients.gender;
SELECT patients.last_name,patients.diagnosis FROM patients;
SELECT patients.last_name,patients.age,patients.diagnosis FROM patients;
SELECT patients.first_name,patients.last_name,patients.age FROM patients;
SELECT patients.last_name,patients.age FROM patients;
SELECT patients.last_name,patients.diagnosis FROM patients;
SELECT patients.last_name,patients.gender FROM patients;
SELECT patients.first_name,patients.last_name FROM patients WHERE patients.age>=20 AND patients.age<=30;
SELECT patients.age FROM patients WHERE patients.length_of_stay>=3;
SELECT patients.age FROM patients WHERE patients.length_of_stay<=3;
SELECT patients.age FROM patients WHERE patients.length_of_stay<3;
SELECT patients.age FROM patients WHERE patients.length_of_stay>3;
SELECT patients.last_name,patients.diagnosis FROM patients WHERE patients.gender='male' OR patients.age>18;
SELECT sum(patients.age) FROM patients;
SELECT max(patients.length_of_stay) FROM patients;
SELECT count(1) FROM patients;
SELECT min(patients.length_of_stay) FROM patients;
SELECT sum(patients.length_of_stay) FROM patients;
SELECT count(1) FROM patients WHERE patients.gender='male' AND patients.age>=18;
SELECT min(patients.length_of_stay) FROM patients WHERE patients.age=18;
SELECT sum(patients.age) FROM patients WHERE patients.diagnosis<>'flu';
SELECT sum(patients.length_of_stay) FROM patients WHERE patients.diagnosis='flu';
SELECT sum(patients.age) FROM patients WHERE patients.age>=20 AND patients.age<=30;
SELECT max(patients.length_of_stay) FROM patients WHERE patients.age<25;
SELECT patients.gender,sum(patients.age) FROM patients GROUP BY patients.gender;
SELECT patients.gender,count(1) FROM patients GROUP BY patients.gender;
SELECT patients.diagnosis,min(patients.length_of_stay) FROM patients GROUP BY patients.diagnosis;
SELECT patients.gender,sum(patients.age) FROM patients WHERE patients.age>=18 GROUP BY patients.gender;
SELECT patients.diagnosis,sum(patients.length_of_stay) FROM patients GROUP BY patients.diagnosis;
SELECT patients.diagnosis,sum(patients.age) FROM patients GROUP BY patients.diagnosis;
SELECT patients.gender,sum(patients.age) FROM patients WHERE patients.length_of_stay<=5 GROUP BY patients.gender;
SELECT patients.diagnosis,sum(patients.length_of_stay) FROM patients WHERE patients.age>=20 AND patients.age<=30 GROUP BY patients.diagnosis;
SELECT patients.diagnosis,sum(patients.age) FROM patients WHERE patients.length_of_stay<6 GROUP BY patients.diagnosis;
SELECT patients.gender,sum(patients.age) FROM patients WHERE patients.diagnosis<>'flu' GROUP BY patients.gender;
SELECT patients.gender,count(1) FROM patients WHERE patients.age>=10 AND patients.age<=25 GROUP BY patients.gender;
SELECT patients.diagnosis,min(patients.length_of_stay) FROM patients WHERE patients.first_name='John' GROUP BY patients.diagnosis;
SELECT patients.first_name,patients.last_name FROM patients;
SELECT distinct(patients.diagnosis) FROM patients;
SELECT patients.first_name,patients.last_name FROM patients WHERE patients.diagnosis='flu';
SELECT patients.first_name,patients.last_name FROM patients WHERE patients.diagnosis<>'flu';
SELECT max(patients.age) FROM patients;
SELECT avg(patients.length_of_stay) FROM patients;
SELECT max(patients.age) FROM patients WHERE patients.gender='female' AND patients.age>=18;
SELECT avg(patients.length_of_stay) FROM patients WHERE patients.age=15;
SELECT patients.diagnosis,avg(patients.length_of_stay) FROM patients GROUP BY patients.diagnosis;
SELECT patients.diagnosis,avg(patients.length_of_stay) FROM patients WHERE patients.gender='male' GROUP BY patients.diagnosis;
